// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe_8Oz0GITOi0-WbcClPPySZrKsRnm8Vg',
    appId: '1:835024232739:web:126c75040492ba0e0c2c96',
    messagingSenderId: '835024232739',
    projectId: 'smart-home-monitoring-sy-48629',
    authDomain: 'smart-home-monitoring-sy-48629.firebaseapp.com',
    databaseURL: 'https://smart-home-monitoring-sy-48629-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-monitoring-sy-48629.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDta45QuAqA16nVEIATiVB9Szmzz0lAmrg',
    appId: '1:835024232739:android:3ec383553cfd58080c2c96',
    messagingSenderId: '835024232739',
    projectId: 'smart-home-monitoring-sy-48629',
    databaseURL: 'https://smart-home-monitoring-sy-48629-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-monitoring-sy-48629.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMg5HxuePG5OWoBDQGqyNH-wcInh1oU9c',
    appId: '1:835024232739:ios:26e4f58cad671a1d0c2c96',
    messagingSenderId: '835024232739',
    projectId: 'smart-home-monitoring-sy-48629',
    databaseURL: 'https://smart-home-monitoring-sy-48629-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-monitoring-sy-48629.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeMonitor',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMg5HxuePG5OWoBDQGqyNH-wcInh1oU9c',
    appId: '1:835024232739:ios:26e4f58cad671a1d0c2c96',
    messagingSenderId: '835024232739',
    projectId: 'smart-home-monitoring-sy-48629',
    databaseURL: 'https://smart-home-monitoring-sy-48629-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-monitoring-sy-48629.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe_8Oz0GITOi0-WbcClPPySZrKsRnm8Vg',
    appId: '1:835024232739:web:2c8fdbc042b9e5460c2c96',
    messagingSenderId: '835024232739',
    projectId: 'smart-home-monitoring-sy-48629',
    authDomain: 'smart-home-monitoring-sy-48629.firebaseapp.com',
    databaseURL: 'https://smart-home-monitoring-sy-48629-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-monitoring-sy-48629.firebasestorage.app',
  );
}
